spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.create_namespaces: true
      hibernate.default_schema: wbg

  flyway:
    default-schema: wbg
    schemas: wbg
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 1

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always   # Flyway owns the schema objects
      table-name: wbg.spring_session

  ai:
    openai:
      enabled: true
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
    azure:
      openai:
        enabled: false
    anthropic:
      enabled: false

  files:
    extractor:
      enabled: true

springdoc:
  enable-data-rest: false
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /v3/api-docs
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoint:
    health:
      show-details: always
